// Product data transcribed from the live SpotON clearance pages (spotonsupplies.co.za), 2026-07-10.
// Prices are "each, excluding VAT" as shown on the product images.
// To update: edit price / pack / qty per item. Set price to null to show "Enquire for price".
const CLEARANCE_ITEMS = [
  // ---------- GLASSWARE (price ea ex VAT, sold per pack) ----------
  { cat: "glassware", name: "Grande-S Whiskey 310ml", code: "52060", img: "assets/clearance/glassware-52060.jpg", price: 15.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Timeless Champagne Flute 175ml", code: "440356", img: "assets/clearance/glassware-440356.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Highness Long Drink 355ml", code: "520065", img: "assets/clearance/glassware-520065.jpg", price: 19.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "City Juice 190ml", code: "52456", img: "assets/clearance/glassware-52456.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Hudson Martini 230ml", code: "440263", img: "assets/clearance/glassware-440263.jpg", price: 21.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Imperial Beer 340ml", code: "42376", img: "assets/clearance/glassware-42376.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Pleasure Long Drink 480ml", code: "420235", img: "assets/clearance/glassware-420235.jpg", price: 21.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Bistro Beer Stem 400ml", code: "44417", img: "assets/clearance/glassware-44417.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Reserva Champagne Flute 185ml", code: "67076", img: "assets/clearance/glassware-67076.jpg", price: 25.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Timeless Jug 1.44L", code: "55332", img: "assets/clearance/glassware-55332.jpg", price: 59.99, pack: 1, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Pleasure Whiskey 350ml", code: "420064", img: "assets/clearance/glassware-420064.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Allegra Whiskey 345ml", code: "420184", img: "assets/clearance/glassware-420184.jpg", price: 29.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Hill Long Drink 440ml", code: "420204", img: "assets/clearance/glassware-420204.jpg", price: 15.99, pack: 3, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Amber Stemless Wine 350ml", code: "420825T", img: "assets/clearance/glassware-420825t.jpg", price: 9.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Hill Whiskey 300ml", code: "420945", img: "assets/clearance/glassware-420945.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Pub Pilsner 320ml", code: "42199", img: "assets/clearance/glassware-42199.jpg", price: 8.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Village Carafe 250ml", code: "43804", img: "assets/clearance/glassware-43804.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Village Carafe 500ml", code: "43814", img: "assets/clearance/glassware-43814.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Village Carafe 100ml", code: "43818", img: "assets/clearance/glassware-43818.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Maldive Flute 180ml", code: "440041", img: "assets/clearance/glassware-440041.jpg", price: 19.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Allegra White Wine 350ml", code: "440080V", img: "assets/clearance/glassware-440080v.jpg", price: 19.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Timeless Martini 230ml", code: "440176", img: "assets/clearance/glassware-440176.jpg", price: 39.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Amber Wine 350ml", code: "440265", img: "assets/clearance/glassware-440265.jpg", price: 15.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Amber Wine 460ml (187 line mark)", code: "440275-187pcl", img: "assets/clearance/glassware-440275-187pcl.jpg", price: 15.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Amber Wine 460ml", code: "440275", img: "assets/clearance/glassware-440275.jpg", price: 24.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Elysia Martini 220ml", code: "440328", img: "assets/clearance/glassware-440328.jpg", price: 29.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Stemmed Liqueur Glass 60ml", code: "44134", img: "assets/clearance/glassware-44134.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Bistro Martini 190ml", code: "44410", img: "assets/clearance/glassware-44410.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Imperial Plus 310ml", code: "44809", img: "assets/clearance/glassware-44809.jpg", price: 15.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Imperial Plus 420ml", code: "44829", img: "assets/clearance/glassware-44829.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Capri Cocktail 380ml", code: "44872", img: "assets/clearance/glassware-44872.jpg", price: 15.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Maldive Wine 251ml", code: "44992", img: "assets/clearance/glassware-44992.jpg", price: 19.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Grande Sunray Long Drink 195ml", code: "520420", img: "assets/clearance/glassware-520420.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "City Long Drink 340ml", code: "52476", img: "assets/clearance/glassware-52476.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "City Whiskey 345ml", code: "52486", img: "assets/clearance/glassware-52486.jpg", price: 8.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Casablanca Long Drink 475ml", code: "52707", img: "assets/clearance/glassware-52707.jpg", price: 15.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Timeless Shooter 60ml", code: "52780", img: "assets/clearance/glassware-52780.jpg", price: 9.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Timeless Long Drink 450ml", code: "52800", img: "assets/clearance/glassware-52800.jpg", price: 35.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Irish Coffee Mug 225ml", code: "55141", img: "assets/clearance/glassware-55141.jpg", price: 19.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Vela Mug 250ml", code: "55201", img: "assets/clearance/glassware-55201.jpg", price: 8.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Reserva Red Wine 580ml (250ml line mark)", code: "67079(250-line)", img: "assets/clearance/glassware-67079-250-line.jpg", price: 29.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Reserva Red Wine 580ml", code: "67079", img: "assets/clearance/glassware-67079.jpg", price: 25.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Bacchus Carafe 250ml", code: "80112", img: "assets/clearance/glassware-80112.jpg", price: 25.99, pack: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Bacchus Carafe 500ml", code: "80113", img: "assets/clearance/glassware-80113.jpg", price: 19.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Tour Votive Blue", code: "NX040U1", img: "assets/clearance/glassware-nx040u1.jpg", price: 25.99, pack: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "glassware", name: "Festival Jug 1.8L", code: "XL-55102", img: "assets/clearance/glassware-xl-55102.jpg", price: 120.00, pack: 6, email: "schanel@spotonsupplies.co.za" },

  // ---------- CROCKERY (price ea ex VAT, limited quantities) ----------
  { cat: "crockery", name: "Studio Prints Oval Plate", size: "34.7cm x 17.3cm", code: "CC-AGBL-OV35.1", img: "assets/clearance/crockery-cc-agbl-ov35-1.jpg", price: 359.96, qty: 65, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Bit On The Side Dip Pot", size: "5.9cm", code: "CC-BCBL-RPD2.1", img: "assets/clearance/crockery-cc-bcbl-rpd2-1.jpg", price: 37.46, qty: 35, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Bit On The Side Ripple Dip Dish", size: "11.3cm", code: "CC-BCBL-RPDD.1", img: "assets/clearance/crockery-cc-bcbl-rpdd-1.jpg", price: 30.71, qty: 23, email: "adminpta@spotonsupplies.co.za" },
  { cat: "crockery", name: "Emerge Medium Deep Bowl", size: "5.9cm h x 12cm dia", code: "CC-EMGY-EM16.1", img: "assets/clearance/crockery-cc-emgy-em16-1.jpg", price: 122.96, qty: 24, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Emerge Rectangular Plate", size: "30cm x 14.7cm", code: "CC-EMGY-EP30.1", img: "assets/clearance/crockery-cc-emgy-ep30-1.jpg", price: 193.31, qty: 17, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Emerge Shallow Tray", size: "17.3cm x 11.9cm x 3.3cm", code: "CC-EMGY-ET17.1", img: "assets/clearance/crockery-cc-emgy-et17-1.jpg", price: 91.93, qty: 15, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Emerge Ramen Bowl", size: "8cm h x 20cm dia", code: "CC-EMGY-EU20.1", img: "assets/clearance/crockery-cc-emgy-eu20-1.jpg", price: 143.21, qty: 19, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Finca Organic Rectangular Plate", size: "27cm x 16cm", code: "CC-MCFL-DOB1.1", img: "assets/clearance/crockery-cc-mcfl-dob1-1.jpg", price: 263.96, qty: 9, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Raku Coupe Plate", size: "26cm", code: "CC-RKBQ-EV10.1", img: "assets/clearance/crockery-cc-rkbq-ev10-1.jpg", price: 153.71, qty: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Raku Coupe Plate", size: "26cm", code: "CC-RKTB-EV10.1", img: "assets/clearance/crockery-cc-rktb-ev10-1.jpg", price: 128.21, qty: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Raku Organic Round Bowl", size: "25.3cm", code: "CC-RKTB-OGB1.1", img: "assets/clearance/crockery-cc-rktb-ogb1-1.jpg", price: 333.56, qty: 11, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Raku Oval Coupe Plate", size: "31.7cm x 25.5cm", code: "CC-RKTB-OP12.1-P", img: "assets/clearance/crockery-cc-rktb-op12-1-p.jpg", price: 275.16, qty: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Milk Jug", size: "11.4cl", code: "CC-SDES-SJ4.1", img: "assets/clearance/crockery-cc-sdes-sj4-1.jpg", price: 106.46, qty: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Zest Bowl", size: "12.1cm x 6.5cm", code: "CC-SDES-ZE12.1", img: "assets/clearance/crockery-cc-sdes-ze12-1.jpg", price: 70.09, qty: 11, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Walled Plate", size: "27.5cm", code: "CC-SPGS-WP28.1", img: "assets/clearance/crockery-cc-spgs-wp28-1.jpg", price: 155.85, qty: 5, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Raw Coupe Plate", size: "28.8cm", code: "CC-SRGY-EV11.1", img: "assets/clearance/crockery-cc-srgy-ev11-1.jpg", price: 188.21, qty: 11, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Raw Coupe Bowl", size: "18.2cm", code: "CC-SRTE-EVB7.1", img: "assets/clearance/crockery-cc-srte-evb7-1.jpg", price: 122.96, qty: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Saucer", size: "15.6cm", code: "CC-SSOS-CSS.1", img: "assets/clearance/crockery-cc-ssos-css-1.jpg", price: 59.21, qty: 59, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Mug", size: "34cl", code: "CC-SSOS-VM12.1", img: "assets/clearance/crockery-cc-ssos-vm12-1.jpg", price: 100.46, qty: 48, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stone Oblong Chefs' Plate", size: "30cm x 15.3cm", code: "CC-STAG-XO11.1", img: "assets/clearance/crockery-cc-stag-xo11-1.jpg", price: 228.12, qty: 11, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Stonecast Triangle Plate", size: "22.9cm", code: "CC-SWHS-TR9.1", img: "assets/clearance/crockery-cc-swhs-tr9-1.jpg", price: 116.96, qty: 24, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Whiteware Sugar Sachet Holder", size: "11cm x 7cm", code: "CC-WH-SH.1", img: "assets/clearance/crockery-cc-wh-sh-1.jpg", price: 145.46, qty: 11, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Omada Stackable Dinner Plate", size: "26cm", code: "IBOM-36", img: "assets/clearance/crockery-ibom-36.jpg", price: 76.91, qty: 12, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Omada Stackable Side Plate", size: "21cm", code: "IBOM-37", img: "assets/clearance/crockery-ibom-37.jpg", price: 71.47, qty: 6, email: "schanel@spotonsupplies.co.za" },
  { cat: "crockery", name: "Omada Stackable Cereal Bowl", size: "15cm x 5cm", code: "IBOM-45", img: "assets/clearance/crockery-ibom-45.jpg", price: 77.52, qty: 12, email: "schanel@spotonsupplies.co.za" }
];
